Intex2ABBCAuthentication/Models/Prediction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Intex2ABBCAuthentication.Models
{
    public class Prediction
    {
        public float PredictedValue { get; set; }
        public CarCrash crash { get; set; }
    }
}

Intex2ABBCAuthentication/Components/FilterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Intex2ABBCAuthentication.Components
{
    public class FilterViewComponent : ViewComponent
    {
        public FilterViewComponent()
        {
        }
        public async  Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Intex2ABBCAuthentication/Controllers/HomeController.cs
using Intex2ABBCAuthentication.Models;
using Intex2ABBCAuthentication.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace Intex2ABBCAuthentication.Controllers
{



    public class HomeController : Controller
    {
        public string City { get; set; }
        public string County { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public double Severity { get; set; }
        public CrashFilter filter { get; set; }

        private readonly ILogger<HomeController> _logger;
        private ICrashRepository repo;
        private InferenceSession _session;

        public HomeController(ILogger<HomeController> logger, ICrashRepository temp, InferenceSession session)
        {
            _logger = logger;
            repo = temp;
            _session = session;

        }



        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Prediction(Prediction prediction)
        {
             var   stuff = new Prediction { PredictedValue = (float)0.0 };

            ViewBag.Pred = stuff;
            return View();
        }
        [HttpPost]
        public IActionResult Prediction(CarCrash data)
        {
            var result = _session.Run(new List<NamedOnnxValue>
                {
                NamedOnnxValue.CreateFromTensor("float_input", data.AsTensor())
                });
            Tensor<float> score = result.First().AsTensor<float>();
            var prediction = new Prediction { PredictedValue = score.First(), crash = data };
            result.Dispose();

            var stuff = prediction;
            ViewBag.Pred = stuff;

            return View(data);
        }

        [HttpGet]
        public IActionResult SummaryInitial()
        {
            var things = new IntegersUsed(repo, 10)
            {
                Crashes2 = repo.Crashes.AsEnumerable()
            };

            return View("SummaryData", things);
        }

        public PageInfo GetPageInfo(int totalItems, int currentPage = 1, int pageSize = 10, int maxPages = 10)
        {
            var totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);

            // ensure current page isn't out of range
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            else if (currentPage > totalPages)
            {
                currentPage = totalPages;
            }

            int startPage, endPage;
            if (totalPages <= maxPages)
            {
                // total pages less than max so show all pages
                startPage = 1;
                endPage = totalPages;
            }
            else
            {
                // total pages more than max so calculate start and end pages
                var maxPagesBeforeCurrentPage = (int)Math.Floor((decimal)maxPages / (decimal)2);
                var maxPagesAfterCurrentPage = (int)Math.Ceiling((decimal)maxPages / (decimal)2) - 1;
                if (currentPage <= maxPagesBeforeCurrentPage)
                {
                    // current page near the start
                    startPage = 1;
                    endPage = maxPages;
                }
                else if (currentPage + maxPagesAfterCurrentPage >= totalPages)
                {
                    // current page near the end
                    startPage = totalPages - maxPages + 1;
                    endPage = totalPages;
                }
                else
                {
                    // current page somewhere in the middle
                    startPage = currentPage - maxPagesBeforeCurrentPage;
                    endPage = currentPage + maxPagesAfterCurrentPage;
                }
            }

            // calculate start and end item indexes
            var startIndex = (currentPage - 1) * pageSize;
            var endIndex = Math.Min(startIndex + pageSize - 1, totalItems - 1);

            // create an array of pages that can be looped over
            var pages = Enumerable.Range(startPage, (endPage + 1) - startPage);

            // update object instance with all pager properties required by the view
            var PageInfo = new PageInfo
            {
                TotalNumCrashes = totalItems,
                CrashesPerPage = pageSize,
                CurrentPage = currentPage,
                StartPage = startPage,
                EndPage = endPage,
                StartIndex = startIndex,
                EndIndex = endIndex,
                Pages = pages
            };
            return PageInfo;
        }
        [HttpGet]
        public IActionResult SummaryData(int pageNum = 1)
        {
            int pageSize = 10;

            var things = new CrashViewModel()
            {
                CarCrashes = repo.Crashes
                    .AsEnumerable()
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize),
                PageInfo = GetPageInfo(repo.Crashes.Count(), pageNum, 10, 10)
            };

            ViewBag.PageNum = pageNum;
            return View(things);
        }


        [HttpPost]
        public IActionResult SummaryData(int m = 0, int y = 0, string c = null, string co = null, double s = 0)
        {
            var pageNum = 1;
            var pageSize = 10;

            int month = m;
            int year = y;
            string city = c;
            string county = co;
            double severity = s;

            IEnumerable<CarCrash> bigQuery;

            //10000
            if (month != 0 && year == 0 && city == null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Month == month select crash;
            }
            //11000
            else if (month != 0 && year != 0 && city == null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Month == month && crash.crash_date.Year == year select crash;
            }
            //111000
            else if (month != 0 && year != 0 && city != null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Month == month && crash.crash_date.Year == year && crash.city == city select crash;
            }
            //11110
            else if (month != 0 && year != 0 && city != null && county != null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Month == month && crash.crash_date.Year == year && crash.city == city && crash.county_name == county select crash;
            }
            //11111
            else if (month != 0 && year != 0 && city != null && county != null && severity != 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Month == month && crash.crash_date.Year == year && crash.city == city && crash.county_name == county && crash.crash_severity_id == severity select crash;
            }
            //01000
            else if (month == 0 && year != 0 && city == null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Year == year select crash;
            }
            //01100
            else if (month == 0 && year != 0 && city != null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Year == year && crash.city == city select crash;
            }
            //01110
            else if (month == 0 && year != 0 && city != null && county != null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Year == year && crash.city == city && crash.county_name == county select crash;
            }
            //01111
            else if (month == 0 && year != 0 && city != null && county != null && severity != 0)
            {
                bigQuery = from crash in repo.Crashes where crash.crash_date.Year == year && crash.city == city && crash.county_name == county && crash.crash_severity_id == severity select crash;
            }
            //00100
            else if (month == 0 && year == 0 && city != null && county == null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.city == city select crash;
            }
            //00110
            else if (month == 0 && year == 0 && city != null && county != null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.city == city && crash.county_name == county select crash;
            }
            //00111
            else if (month == 0 && year == 0 && city != null && county != null && severity != 0)
            {
                bigQuery = from crash in repo.Crashes where crash.city == city && crash.county_name == county && crash.crash_severity_id == severity select crash;
            }
            //00010
            else if (month == 0 && year == 0 && city == null && county != null && severity == 0)
            {
                bigQuery = from crash in repo.Crashes where crash.county_name == county select crash;
            }
            //00011
            else if (month == 0 && year == 0 && city == null && county != null && severity != 0)
            {
                bigQuery = from crash in repo.Crashes where crash.county_name == county && crash.crash_severity_id == severity select crash;
            }
            //00001

Intex2ABBCAuthentication/Views/Home/Confirmation.cshtml
@{
    ViewData["Title"] = "Delete Appointment";
}

@model CarCrash

<h2>Confirm Deletion</h2>
<h3>Are you sure you want to delete appointment for the crash in @Model.city?</h3>

<form method="post" asp-action="Delete">
    <button type="submit" class="btn-danger">Delete</button>
    <a asp-controller="Home" asp-action="SummaryData" class="btn btn-primary">Cancel</a>

    <input type="hidden" asp-for="Field1" />
</form>

Intex2ABBCAuthentication/Views/Home/Delete.cshtml
@{
    ViewData["Title"] = "Delete Appointment";
}

@model CarCrash

<h2>Confirm Deletion</h2>
<h3>Are you sure you want to delete this crash from the database?</h3>

<form method="post" asp-action="Delete">
    <button type="submit" class="btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="SummaryData" class="btn btn-primary">Cancel</a>

    <input type="hidden" asp-for="Field1" />
</form>

Intex2ABBCAuthentication/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details Page";
}

@model CarCrash

<h3 class="bg-info text-white text-center">Details</h3>

<table class="table table-sm table-bordered table-striped">

    <tbody>
        @*info on each crash*@
        <tr>
            <th>Crash ID:</th>
            <td>@Model.crash_id</td>
        </tr>


        @if (@Model.crash_severity_id == 1.0)
        {
            <tr>
                <th>Severity:</th>
                <td>
                    No Injury
                </td>
            </tr>
        }
        @if (@Model.crash_severity_id == 2.0)
        {
            <tr>
                <th>Severity:</th>
                <td>
                    Possible Injury
                </td>
            </tr>
        }
        @if (@Model.crash_severity_id == 3.0)
        {
            <tr>
                <th>Severity:</th>
                <td>
                    Suspected Minor Injury
                </td>
            </tr>
        }
        @if (@Model.crash_severity_id == 4.0)
        {
            <tr>
                <th>Severity:</th>
                <td>
                    Suspected Major Injury
                </td>
            </tr>
        }
        @if (@Model.crash_severity_id == 5.0)
        {
            <tr>
                <th>Severity:</th>
                <td>
                    Fatal
                </td>
            </tr>
        }



        <tr><th>Date:</th><td>@Model.crash_date.Month/@Model.crash_date.Day/@Model.crash_date.Year</td></tr>
        <tr><th>Time:</th><td>@Model.crash_time</td></tr>
        <tr><th>County:</th><td>@Model.county_name</td></tr>
        <tr><th>City:</th><td>@Model.city</td></tr>
        <tr><th>Road:</th><td>@Model.main_road_name</td></tr>
        <tr><th>Route:</th><td>@Model.route</td></tr>
        <tr><th>Mile Point:</th><td>@Model.milepoint</td></tr>

        @*Only show the conditions of the crash that are true*@

        @if (Model.Freeway == "True")
        {
            <tr><th>Freeway:</th><td>True</td></tr>
        }
        @if (Model.Holiday == "True")
        {
            <tr><th>Holiday:</th><td>True</td></tr>
        }

        @if (Model.Weekend == "True")
        {
            <tr><th>Weekend:</th><td>True</td></tr>
        }

        @if (Model.bicyclist_involved == 1.0)
        {
            <tr><th>Bicyclist Involvement:</th><td>True</td></tr>
        }

        @if (Model.motorcycle_involved == 1.0)
        {
            <tr><th>Motorcycle Involvement:</th><td>True</td></tr>
        }

        @if (Model.commercial_motor_veh_involved == 1.0)
        {
            <tr><th>Commercial Vehicle Involvement:</th><td>True</td></tr>
        }

        @if (Model.pedestrian_involved == 1.0)
        {
            <tr><th>Pedestrian Involvement:</th><td>True</td></tr>
        }

        @if (Model.dui == 1.0)
        {
            <tr><th>Driving Under the Influence:</th><td>True</td></tr>
        }

        @if (Model.drowsy_driving == 1.0)
        {
            <tr><th>Drowsy Driving:</th><td>True</td></tr>
        }

        @if (Model.distracted_driving == 1.0)
        {
            <tr><th>Distracted Driving:</th><td>True</td></tr>
        }

        @if (Model.domestic_animal_related == 1.0)
        {
            <tr><th>Domestic Animal Related:</th><td>True</td></tr>
        }

        @if (Model.wild_animal_related == 1.0)
        {
            <tr><th>Wild Animal Related:</th><td>True</td></tr>
        }

        @if (Model.improper_restraint == 1.0)
        {
            <tr><th>Improper Use of Restraint:</th><td>True</td></tr>
        }

        @if (Model.unrestrained == 1.0)
        {
            <tr><th>Lack of Restraint:</th><td>True</td></tr>
        }
        @if (Model.work_zone_related == 1.0)
        {
            <tr><th>Work Zone Related:</th><td>True</td></tr>
        }

        @if (Model.intersection_related == 1.0)
        {
            <tr><th>Intersection Related:</th><td>True</td></tr>
        }

        @if (Model.night_dark_condition == 1.0)
        {
            <tr><th>Night Time(Dark):</th><td>True</td></tr>
        }

        @if (Model.older_driver_involved == 1.0)
        {
            <tr><th>Older Driver Involvement:</th><td>True</td></tr>
        }

        @if (Model.teenage_driver_involved == 1.0)
        {
            <tr><th>Teenage Driver Involved:</th><td>True</td></tr>
        }

        @if (Model.overturn_rollover == 1.0)
        {
            <tr><th>Vehicle Overturned:</th><td>True</td></tr>
        }

        @if (Model.roadway_departure == 1.0)
        {
            <tr><th>Crash Ran Vehicle Off Road:</th><td>True</td></tr>
        }

        @if (Model.single_vehicle == 1.0)
        {
            <tr><th>Single Vehicle Crash:</th><td>True</td></tr>
        }

    </tbody>

</table>
@if (User.Identity.IsAuthenticated == true)
{

    <a asp-controller="Home" asp-action="EditCrash" asp-route-fieldid="@Model.Field1" class="col-2 btn btn-secondary">Edit</a>
    <a asp-controller="Home" asp-action="Delete" asp-route-fieldid="@Model.Field1" class="col-2 btn btn-warning">Delete</a>
    <a asp-controller="Home" asp-action="SummaryData" class="col-2 btn btn-primary">Back</a>
}

Intex2ABBCAuthentication/Views/Home/Forecast.cshtml
@{
    ViewData["Title"] = "Forecast";
}

<body>
    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container">

                <div class="d-flex justify-content-between align-items-center">
                    <h2>Forecasting Tool</h2>
                    <ol>
                        <li><a href="https://colab.research.google.com/drive/138SOfKBbTbI3QROqcgaNoDnMKPr80Ftp#scrollTo=B7mhgajwpiNH&line=1&uniqifier=1" target="_blank">View Forecaster</a></li>
                    </ol>
                </div>

            </div>
        </section><!-- End Breadcrumbs -->
        <!-- ======= Portfolio Details Section ======= -->
        <section id="portfolio-details" class="portfolio-details">
            <div class="container">

                <div class="row gy-4">

                    <div class="portfolio-description">
                        <h4>Summary</h4>
                        <p>
                            Simply analyzing trends in accidents on Utah roads doesn't do anything to make a difference in reducing the severity of future accidents. We wanted to create a tool to help policymakers pinpoint important factors in order to make specific, measurable goals to improve road safety. This forecasting tool not only shows the differences between past and projected future trends, it allows users to input theoretical goals for specific factors and see how reaching those goals could impact future trends in accidents.
                        </p>
                        <p>
                            Our forecasting tool uses a Seasonal Autoregressive Integrated Moving Average with Exogenous Regressors (SARIMAX) to predict month-by-month accident trends according to the seasonality seen in the collected data.
                        </p>
                    </div>
                    <div class="col-lg-2">
                        <div class="portfolio-description">
                            <h5>See how reducing certain factors can reduce future accident severity and increase safety on Utah roads.</h5>
                            <p>

                            </p>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="portfolio-details-slider swiper">
                            <div class="swiper-wrapper align-items-center">

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/actuals.jpg" alt="">
                                </div>

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/duififteen.jpg" alt="">
                                </div>

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/pedestrianten.jpg" alt="">
                                </div>

                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>


                    <div class="col-lg-10">
                        <div class="portfolio-details-slider swiper">
                            <div class="swiper-wrapper align-items-center">

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/drowsyfifteen.jpg" alt="">
                                </div>

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/biketen.jpg" alt="">
                                </div>

                                <div class="swiper-slide">
                                    <img src="~/assets/img/portfolio/motorcyclefifteen.jpg" alt="">
                                </div>

                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="portfolio-description">
                            <h5>Set measurable goals and see how reaching those goals will reduce accident severity in Utah. </h5>
                        </div>
                    </div>
                </div>
        </section><!-- End Portfolio Details Section -->

    </main><!-- End #main -->
    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
</body>

Intex2ABBCAuthentication/Views/Home/SummaryData.cshtml
@{
    ViewData["Title"] = "Data";
}
@model Intex2ABBCAuthentication.Models.ViewModels.CrashViewModel
<br />
<br />

<body>
    <div>
        <div class="row">
            <div class="container">
                <div class="col-3">
                    <h3>Crashes List</h3>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <form asp-action="SummaryData" method="post">

                    <div class="form-group">
                        <label for="y">Year</label>
                        <input type="number" maxlength="10" min="2016" class="form-control" id="y" name="y" aria-describedby="emailHelp" placeholder="Enter Year">
                    </div>

                    @*<label>Year</label>
                        <input name="y" />*@


                    @*<div class="form-group">
                            <label for="m">Month</label>
                            <input type="text" class="form-control" id="m" name="m" aria-describedby="emailHelp" placeholder="Select Month">
                        </div>*@

                    <div class="form-group">
                        <label for="m">Month</label>
                        <select name="m" class="form-select" aria-label="Default select example">
                            <option selected disabled style="color:#808080">Select Month</option>
                            <option name="m" value="1">January</option>
                            <option name="m" value="2">February</option>
                            <option name="m" value="3">March</option>
                            <option name="m" value="4">April</option>
                            <option name="m" value="5">May</option>
                            <option name="m" value="6">June</option>
                            <option name="m" value="7">July</option>
                            <option name="m" value="8">August</option>
                            <option name="m" value="9">September</option>
                            <option name="m" value="10">October</option>
                            <option name="m" value="11">November</option>
                            <option name="m" value="12">December</option>
                        </select>
                    </div>
                    @*<label>Month</label>
                        <input name="m" />*@

                    <div class="form-group">
                        <label for="c">City</label>
                        <input type="text" class="form-control" id="c" name="c" aria-describedby="emailHelp" placeholder="Enter City">
                    </div>

                    @*<label>City</label>
                        <input name="c" />*@

                    <div class="form-group">
                        <label for="co">County</label>
                        <input type="text" class="form-control" id="co" name="co" aria-describedby="emailHelp" placeholder="Enter County">
                    </div>

                    @*<label>County</label>
                        <input name="co" />*@


                    @*<div class="form-group">
                            <label for="s">Severity</label>
                            <input type="text" class="form-control" id="s" name="s" aria-describedby="emailHelp" placeholder="Enter Severity">
                        </div>*@
                    <div class="form-group">
                        <label for="s">Severity</label>
                        <select name="s" class="form-select" aria-label="Default select example">
                            <option selected disabled>Select a Severity</option>
                            <option value="1.0">No Injury</option>
                            <option value="2.0">Possible Injury</option>
                            <option value="3.0">Suspected Minor Injury</option>
                            <option value="4.0">Suspected Major Injury</option>
                            <option value="5.0">Fatal</option>
                        </select>
                    </div>
                    @*<label>Severity</label>
                        <input name="s" />*@

                    <br />
                    <div class="float-end">
                        <input class="btn btn-primary" type="submit" value="Filter Results" />
                    </div>

                </form>
            </div>
            <div class="col">
                @foreach (CarCrash c in Model.CarCrashes)
            {
                <partial name="CrashSummary" model="c" />
            }

                <div class="col-9 float-left">
                    <div page-turn="@Model.PageInfo" page-action="SummaryData"
                         page-class="btn" page-class-normal="bg-light"
                         page-class-selected="btn-primary" class="btn-group pull-right m-1"
                         page-class-enabled="true">

                    </div>
                </div>
            </div>


        </div>
    </div>



</body>

Intex2ABBCAuthentication/Views/Home/SummaryInitial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<vc:filter/>

@*@foreach (CarCrash c in Model)
{
    <partial name="CrashSummary" model="c" />
}*@